# Generated by Django 4.0.1 on 2022-01-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
